# frozen_string_literal: true

# Allows emails generated by devise to be viewed at /rails/mailers
class DeviseMailerPreview < ActionMailer::Preview
  def confirmation_instructions
    user = User.new(full_name: "Full Name", username: "username")
    Devise::Mailer.confirmation_instructions user, "faketoken"
  end

  def reset_password_instructions
    user = User.new(full_name: "Full Name", username: "username")
    Devise::Mailer.reset_password_instructions user, "faketoken"
  end

  def unlock_instructions
    user = User.new(full_name: "Full Name", username: "username")
    Devise::Mailer.unlock_instructions user, "faketoken"
  end
end
